# -*- coding: utf-8 -*-
"""QN 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Wn-kBjkuzCwtD7R34TqVIKYmj3hnwMz
"""

print("Name         : Blessy Babu")
print("Address      : Pandari house,  Priyadasrshini Nagar, Chettupuzha P.O, Thrissur")
print("Telephone no : 854462")