# -*- coding: utf-8 -*-
"""QN 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Wn-kBjkuzCwtD7R34TqVIKYmj3hnwMz
"""

width = int(input("Enter the width : "))
height = int(input("Enter the height : "))
area = width*height
print("The area is ",area,"square units")