# -*- coding: utf-8 -*-
"""QN 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Wn-kBjkuzCwtD7R34TqVIKYmj3hnwMz
"""

rad = int(input("Enter the radius of circle : "))
area = 3.14*rad**2
print("The area of circle is ",area,"square units")