# -*- coding: utf-8 -*-
"""QN 7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Wn-kBjkuzCwtD7R34TqVIKYmj3hnwMz
"""

name = input("Enter your name : ")
age = int(input("Enter your age : "))
print("Your name is",name,"and your age is",age)