# -*- coding: utf-8 -*-
"""QN 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Wn-kBjkuzCwtD7R34TqVIKYmj3hnwMz
"""

num = int(input("Enter a number :"))
print("By adding 1 to",num,"we get",num+1)