# -*- coding: utf-8 -*-
"""QN 9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Wn-kBjkuzCwtD7R34TqVIKYmj3hnwMz
"""

name = input("Enter your first name :")
print(name)